version: "3.3"

services:
  runtask-service:
    image: ruby:2.7.4
    container_name: "tfe_local_runtask_service"
    networks:
      default:
        aliases: [runtask.tfe.zone]
      tfcdev:
        aliases: [runtask.tfe.zone]
    command: ruby /tmp/server.rb
    ports:
      - "28080:8080"
    volumes:
      - "./tmp/local-runtask/server.rb:/tmp/server.rb:ro"
    restart: "always"

  nginx-https:
    image: quay.io/hashicorp/hc-atlas-nginx:1.0.0
    container_name: "tfe_local_nginx_https"
    depends_on:
      - nginx
    entrypoint: >-
      sh /tmp/https_entrypoint.sh
    environment:
      TFE_FQDN: "${TFE_FQDN}"
      TFLOCAL_CLOUD: "${TFLOCAL_CLOUD:-}"
    networks:
      default:
        aliases: [localhttps.tfe.zone]
      tfcdev:
        aliases: [localhttps.tfe.zone]
    ports:
      - "443:443"
    volumes:
      - "./tmp/local-nginxhttps/ssl:/etc/nginx/ssl"
      - "./docker/nginx/entrypoint.sh:/tmp/entrypoint.sh:ro"
      - "./docker/nginx/htpasswd:/etc/nginx/htpasswd:ro"
      - "./tmp/local-nginxhttps/nginx.conf.template:/tmp/nginx.conf.template:ro"
      - "./tmp/local-nginxhttps/https_entrypoint.sh:/tmp/https_entrypoint.sh:ro"
      - "./tmp/local-nginxhttps/internal-ca.crt:/etc/nginx/internal-ca.crt:ro"
      - "./tmp/local-nginxhttps/internal-ca.pem:/etc/nginx/internal-ca.pem:ro"
    restart: "always"

  atlas:
    # Keep the container alive
    # command: tail -f /dev/null
    # Run a simple TCP forwarder to the host instance
    command: /bin/sh -c "apk add socat && socat TCP-LISTEN:3000,fork TCP:host.docker.internal:3000"
    environment:
      SKIP_EMBER: "true"
    volumes:
      - type: bind
        source: ./tmp/ember-cli
        target: /app/tmp/ember-cli

  registry:
    ports:
      - "23121:3121"

  terraform-state-parser:
    ports:
      - "27588:7588"

  slug-ingress:
    ports:
      - "27586:7586"

  tf-vcs:
    ports:
      - "27678:7678"

  tfe-queue-manager:
    ports:
      - "27676:7676"

  tf-cloud-billing:
    ports:
      - "27677:7677"

  archivist:
    ports:
      - "27675:7675"

  rabbitmq:
    ports:
      - "25672:5672"

  redis-cache:
    ports:
      - "26380:6379"

  outbound-http-proxy:
    # Allows http://host.docker.internal:8080 style addresses for the Run Task
    command: ./outbound-http-proxy --config-file config.yaml --allow-range 192.168.0.0/16 --allow-range 172.16.0.0/12
    ports:
      - "28888:8888"
